version: "3"

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    hostname: microservice-ecosystem-rabbitmq
    ports: 
      - "15672:15672"
    networks:
      - microservice-ecosystem-network

  microservice-ecosystem-node-discovery:
    image: microservice-ecosystem-node-discovery:1.0
    container_name: microservice-ecosystem-node-discovery
    hostname: discovery-server
    ports:
      - "10001:80"
    environment:
      - PORT=80
    networks:
      - microservice-ecosystem-network

  microservice-ecosystem-node-configserver:
    image: microservice-ecosystem-node-configserver:1.0
    container_name: microservice-ecosystem-node-configserver
    hostname: config-server
    ports:
      - "10002:80"
    environment:
      - PORT=80
    networks:
      - microservice-ecosystem-network

  microservice-ecosystem-node-apigateway:
    image: microservice-ecosystem-node-apigateway:1.0
    container_name: microservice-ecosystem-node-apigateway
    ports:
      - "10003:80"
    environment:
      - PORT=80
    networks:
      - microservice-ecosystem-network

networks:
  microservice-ecosystem-network:
    name: microservice-ecosystem-network

