spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
      - id: OrderModule
        uri: lb://order
        predicates:
        - Path=/order/**
        filters:
        - CustomFilter

server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY:http://localhost:10001/eureka/}