spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/selimgul/config-server.git
          search-paths: config
server:
  port: ${PORT:80}